from __future__ import annotations

from typing import TypedDict

from betterproto import Message
from betterproto.lib.google.protobuf import Any as GoogleAny


class MessageGenerated(TypedDict):
    """Structure of message generated by our library."""

    message: Message
    """Actual message instance."""
    path: str
    """Path where this was generated inside the library."""


def create_any_message(msg: MessageGenerated) -> GoogleAny:
    """Wrap message (coerced to binary) with convenience wrapper.

    Returns:
        :class:`~betterproto.lib.google.protobuf.Any`
    """
    return GoogleAny(
        type_url=f'/{msg["path"]}',
        value=bytes(msg['message']),
    )
