# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: evmos/vesting/v1/vesting.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from datetime import datetime
from typing import List

import betterproto

from ....cosmos.vesting import v1beta1 as ___cosmos_vesting_v1_beta1__


@dataclass(eq=False, repr=False)
class ClawbackVestingAccount(betterproto.Message):
    """
    ClawbackVestingAccount implements the VestingAccount interface. It provides
    an account that can hold contributions subject to "lockup" (like a
    PeriodicVestingAccount), or vesting which is subject to clawback
    of unvested tokens, or a combination (tokens vest, but are still locked).
    """

    base_vesting_account: "___cosmos_vesting_v1_beta1__.BaseVestingAccount" = (
        betterproto.message_field(1)
    )
    """
    base_vesting_account implements the VestingAccount interface. It contains
    all the necessary fields needed for any vesting account implementation
    """

    funder_address: str = betterproto.string_field(2)
    """funder_address specifies the account which can perform clawback"""

    start_time: datetime = betterproto.message_field(3)
    """start_time defines the time at which the vesting period begins"""

    lockup_periods: List["___cosmos_vesting_v1_beta1__.Period"] = (
        betterproto.message_field(4)
    )
    """lockup_periods defines the unlocking schedule relative to the start_time"""

    vesting_periods: List["___cosmos_vesting_v1_beta1__.Period"] = (
        betterproto.message_field(5)
    )
    """vesting_periods defines the vesting schedule relative to the start_time"""
