from __future__ import annotations

from dataclasses import dataclass

from evmos.eip712 import EIPToSign
from evmos.proto.transactions import TxGeneratedBase as TxGeneratedBase


@dataclass
class Fee:
    """Fee for message."""

    amount: str
    denom: str
    gas: str


@dataclass
class Sender:
    """Message sender."""

    account_address: str
    sequence: int
    account_number: int
    pubkey: str


@dataclass
class Chain:
    """Chain definition."""

    chain_id: int
    cosmos_chain_id: str


@dataclass
class TxGenerated(TxGeneratedBase):
    """Transaction generated by this library (with EIP to sign)."""

    eip_to_sign: EIPToSign
