from __future__ import annotations

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: cosmos/genutil/v1beta1/genesis.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass(eq=False, repr=False)
class GenesisState(betterproto.Message):
    """GenesisState defines the raw genesis transaction in JSON."""

    gen_txs: list[bytes] = betterproto.bytes_field(1)
    """gen_txs defines the genesis transactions."""
