name: PyPi deployment

on:
  push:
    tags: ['*']

permissions:
  contents: read

jobs:
  deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: false

      - name: Build
        run: uv build
      - name: Build
        run: uv publish
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN }}

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') }}
          make_latest: ${{ !contains(github.ref, 'alpha') && !contains(github.ref, 'beta') }}
          generate_release_notes: true
          files: dist/*
